# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kabbage Tech Blog
email: engteam@kabbage.com
description: > # this means to ignore newlines until "baseurl:"
  Kabbage Technology Team blog. Insights into the technology and people
  that make the Kabbage Platform happen. Topics include engineering,
  infrastructure, operations, and data science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techblog.kabbage.com" # the base hostname & protocol for your site
github_username:  kabbageinc

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
    input: GFM
